### PR TITLE
Feat/for approval logic

### LINKED ISSUE #153: code for sending request approval to auditor

### PR DESCRIPTION
**Pull request by yell66w**
# Description

- Linagay ko yung flow nung pag accept sa cash-advance
- Katapos mag run, mapupunta yung CA sa for-approval/requests ng auditor
- Pwede niya i-accept or decline yung CA
- Yung function lang yung inuna ko hindi yung UI kasi tinatamad ako magdesign haha
- Merge mo lang to if na merge na yung #252

Fixes #153 
Depends on #252  

# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)

Screenshot_20220217_233529
Screenshot_20220217_233532
Screenshot_20220217_233536

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by franzegos** [comment]
Nice nice, pwede narin ba dito sa branch na to gawin yung frontend nung for approval bago imerge?

**Comment by CloudyMushroom** [comment]
Check ko if all goods, QA

**Comment by CloudyMushroom** [comment]
- May automatic na nagaappear na error both sides ng auditor and encoder
- Walang nag reflect auditor/for-approval na requests galing sa encoder CA
- Cause siguro yung error kaya di nagru-run maayos


image
image
image
image

**Comment by yell66w** [comment]
> * May automatic na nagaappear na error both sides ng auditor and encoder
> * Walang nag reflect auditor/for-approval na requests galing sa encoder CA
> * Cause siguro yung error kaya di nagru-run maayos
> 
> image image image image

Hindi ata naka run yung server nyo dito sir lodi

**Pull request closed without merging**
