### PR TITLE
Attendance Page UI

### PR DESCRIPTION
**Pull request by yell66w**
# Description

Initial UI lang nung attendance page
Yung tbl.attendance dinidisplay niya diyan haha
Random value lang yung accuracy since wala pang value din sa server

Fixes # (issue)

# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)
Screenshot_React App - Google Chrome_1

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by franzegos** [comment]
goods priii, eto nalang muna:
1. Add date 
2. revise schedule to checkbox: 
Schedule:
6:00 am -  2:30 pm 
2:00 pm – 10:30 pm
10:00 pm – 6:30 am
7:00 am – 4:00 pm
8:30 am – 5:30 pm
9:00 am – 6:00 pm
8:00 am – 5:00 pm

**Comment by franzegos** [comment]
test

**Comment by Deadeyeee** [comment]
WEH

**Comment by franzegos** [comment]
goods priii, eto nalang muna para dito sa attendance:

1. Add date
2. revise schedule to checkbox:
    Schedule: 
    6:00 am - 2:30 pm
    2:00 pm – 10:30 pm
    10:00 pm – 6:30 am
    7:00 am – 4:00 pm
    8:30 am – 5:30 pm
    9:00 am – 6:00 pm
    8:00 am – 5:00 pm

**Comment by yell66w** [comment]
> goods priii, eto nalang muna para dito sa attendance:
> 
> 1. Add date
> 2. revise schedule to checkbox:
>    Schedule:
>    6:00 am - 2:30 pm
>    2:00 pm – 10:30 pm
>    10:00 pm – 6:30 am
>    7:00 am – 4:00 pm
>    8:30 am – 5:30 pm
>    9:00 am – 6:00 pm
>    8:00 am – 5:00 pm

sa filter component po ata yung no.2 ? bali bagong issue siguro to

**Comment by franzegos** [comment]
May conflicts pala kuys

**Comment by yell66w** [comment]
Naresolved na conflicts kaso may bug ako na nadiscover. Hindi pala responsive yung table natin tsaka yung menu pag marami na yung column sa table. Need ata lagyan ng new issue dito sa responsiveness ng table tsaka menu (css-related)

Screenshot_20220215_214240

**Comment by franzegos** [comment]
Bale after maayos nung responsiveness ng table tsaka i-mmerge to?

**Comment by yell66w** [comment]
> Bale after maayos nung responsiveness ng table tsaka i-mmerge to?

Pwede mo siya imerge pre tapos gagawa nalang bagong issue na hindi responsive yung sa table natin tsaka yung menu

**Comment by franzegos** [comment]
> > Bale after maayos nung responsiveness ng table tsaka i-mmerge to?
> 
> Pwede mo siya imerge pre tapos gagawa nalang bagong issue na hindi responsive yung sa table natin tsaka yung menu

copyy

**Pull request merged**
