### PR TITLE
UI/payslip

### PR DESCRIPTION
**Pull request by CloudyMushroom**
# Description

Pa merge na lang po from encoder/employee files -> payslip to auditor/payroll 

Fixes # (issue)

# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ /] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)

Add screenshots that could help the reviewer.

# Checklist:

-   [/ ] My code follows the style guidelines of this project
-   [ /] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by franzegos** [comment]
Saan maoopen yung payslip pre if ma merge sa auditor/payroll? Siguro since wala pa yung "view" sa auditor/payroll pwede muna tapusin yung layout ng payslip dyan sa payslip button ng encoder/employeefiles?

**Comment by CloudyMushroom** [comment]
Oo kaso na push ko na dito priii

**Comment by CloudyMushroom** [comment]
I suggest na magtable doon sa columns ng  attendance, deduction at sa gray background.  may layout na yun, content na lang kulang and I will leave it to you guys since imported yung table na'tin which is wala akong idea pano gamitin

**Comment by yell66w** [comment]
San po ito??

**Comment by yell66w** [comment]
Ah sa auditor->employee file->Employee->Folder->Payslip

**Comment by yell66w** [comment]
Pacheck nga nito @franzegos or @CloudyMushroom . Nasa auditor->employee file->payslip  yung modal.

**Pull request merged**
