### PR TITLE
Feat/nextjs-upgrade (Merge this first!)

### LINKED ISSUE #251: Nextjs upgrade

### PR DESCRIPTION
**Pull request by yell66w**
# Description

- Inupgrade ko sa NextJS yung project natin para medyo maging malinis yung routing.
- Pahanap po ako ng mga error bago imerge (Yung mga error na wala sa dev pero nandito)
- Pacheck din po if may mga kulang na pages or mga components
- Yung Sidebar na Link ewan ko ano nangyari hahaha pahelp po ako paayos nung sidebar @CloudyMushroom 

**IMPORTANT!!**
Gawa po kayo ng .env.local sa root directory ng frontend (Depende sa Database Account niyo po yan)
Ito po contents
```
DB_HOST=127.0.0.1
DB_USER=root
DB_PASS=root
DB_NAME=rdi_payroll_system
DB_PORT=3306
PORT=8000
NODE_ENV=development
NEXTAUTH_SECRET=RDIPAYROLLSYSTEM143
NEXTAUTH_URL=http://localhost:3000/
```

**Tsaka mag npm install din po kayo** 

Fixes #251 
Fixes #243

# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)
Screenshot_20220217_194853

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by franzegos** [comment]
Yung mga error dito pre same lang sya sa dev e, wala naman addtnl error

**Comment by yell66w** [comment]
> Yung mga error dito pre same lang sya sa dev e, wala naman addtnl error

Nice nice buti naman

**Comment by CloudyMushroom** [comment]
image
- Walang appearing error message kapag invalid account login

**Comment by yell66w** [comment]
> image
> 
> * Walang appearing error message kapag invalid account login

Pacheck po ulit

**Comment by yell66w** [comment]
Merge na ba to? hahaha

**Comment by CloudyMushroom** [comment]
image
wala dapat view sa encoder

**Pull request merged**
