### PR TITLE
List View

### LINKED ISSUE #205: Listview Item component

### PR DESCRIPTION
**Pull request by yell66w**
# Description

- Nag useState lang ako, tinatamad ako mag redux haha 
- Functional na yung listview tsaka gridview button

Fixes #205 
# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)
Screenshot_20220220_202940

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by CloudyMushroom** [comment]
may babaguhin ako sa codes okay lang ba??

**Comment by CloudyMushroom** [comment]
image
Masyadong angat 'to lalagayan ko lang space

**Comment by yell66w** [comment]
> may babaguhin ako sa codes okay lang ba??

oo pre pull mo nalang to

**Comment by CloudyMushroom** [comment]
GgGG

**Pull request merged**
